/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d4356d64-091c-4a97-8e01-840535208498",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Wee3PTJmd",
    "aws_user_pools_web_client_id": "6rkdmvkl1231309k2u7br73dft",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://umrbsi3jkndw5c4ssnrrzcumhm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
